version: "3.9"

services:
  api:
    build: .
    container_name: ticket-api
    command: npm start
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  worker:
    build: .
    container_name: ticket-worker
    command: npm run worker
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: ticket-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
